http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  userAPI:
    host: 'localhost'
    paths: '/api/user'
serviceEndpoints:
  userService:
    url: 'http://localhost:3000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: user
    apiEndpoints:
      - userAPI
    policies:
      - proxy:
        - action:
            serviceEndpoint: userService